const TaskActionTypes = {
  CREATE_CATEGORIES: "CREATE_CATEGORIES",
  GET_CATEGORIES: "GET_CATEGORIES",
  CLEAR_CATEGORIES: "CLEAR_CATEGORIES",
  REMOVE_CATEGORIES: "REMOVE_CATEGORIES",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
};

export default TaskActionTypes;
